### ISSUE TITLE
issue when creating Fortinet with the Git Hub Solution

### ISSUE THREAD

**Issue by HeShaobo1** [40net-cloud/fortinet-azure-solutions#172]
Dear team, 

When creating a project running in /fortinet-azure-solutions-main/fortinet-azure-solutions-main/FortiGate/Terraform/VNET-Peering

The Fortinet VM cannot be created, please help on this issue

 Error:
azurerm_virtual_machine.fgtbvm: Still creating... [7m30s elapsed]

Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20210602T051811Z', subscription id '53621724-10de-4a6b-85f0-f8a78d823588', tracking id '57856138-c373-4334-bd03-24c6bd663f12', request correlation id 'b2e706f0-2ac2-8f0a-2df2-392889e18a7f'."

  on 03-fortigate.tf line 280, in resource "azurerm_virtual_machine" "fgtavm":
 280: resource "azurerm_virtual_machine" "fgtavm" {

Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20210602T051811Z', subscription id '53621724-10de-4a6b-85f0-f8a78d823588', tracking id '92df99ce-568f-400e-9d8a-30e566d56a48', request correlation id 'b2e706f0-2ac2-8f0a-2df2-392889e18a7f'."

  on 03-fortigate.tf line 465, in resource "azurerm_virtual_machine" "fgtbvm":
 465: resource "azurerm_virtual_machine" "fgtbvm" {

[root@shaoboopsbmwcentos7 VNET-Peering]#

**Comment by jvhoof** [comment]
Hi,

Can you rerun the deployment? With Terraform you can rerun the terraform apply or the deploy.sh with the correct arguments. The state file will review what needs to be redeployed or updated. The error indicates 'InternalServerError' which is an issue on the Azure platform.

Kind regards,

Joeri

**Comment by HeShaobo1** [comment]
Hi Jvhoof,

Thanks for your help, the scripts is used:
/fortinet/fortinet-azure-solutions-main/fortinet-azure-solutions-main/FortiGate/Terraform/VNET-Peering

and the deployment passed the plan, and apply but failed with error.

Also other project failed with same error(Active-Active-ELB-ILB,Active-Passive-ELB-ILB)

I assume the image should has some unknow issue.

 
[logs.txt](https://github.com/40net-cloud/fortinet-azure-solutions/files/6583124/logs.txt)




on Azure side, the error is listed in Azure resource group activity logs:


   "resourceGroupName": "stagingfw02-RG",
    "resourceProviderName": {
        "value": "Microsoft.Compute",
        "localizedValue": "Microsoft.Compute"
    },
    "resourceType": {
        "value": "Microsoft.Compute/virtualMachines",
        "localizedValue": "Microsoft.Compute/virtualMachines"
    },
    "resourceId": "/subscriptions/53621724-10de-4a6b-85f0-f8a78d823588/resourceGroups/stagingfw02-RG/providers/Microsoft.Compute/virtualMachines/stagingfw02-B-VM-FGT",
    "status": {
        "value": "Failed",
        "localizedValue": "Failed"
    },
    "subStatus": {
        "value": "InternalServerError",
        "localizedValue": "Internal Server Error (HTTP Status Code: 500)"
    },
    "submissionTimestamp": "2021-06-02T07:29:36.216049Z",
    "subscriptionId": "53621724-10de-4a6b-85f0-f8a78d823588",
    "tenantId": "b388b808-0ec9-4a09-a414-a7cbbd8b7e9b",
    "properties": {
        "statusCode": "InternalServerError",
        "serviceRequestId": null,
        "statusMessage": "{\"error\":{\"code\":\"InternalServerError\",\"message\":\"Encountered internal server error. Diagnostic information: timestamp '20210602T072802Z', subscription id '53621724-10de-4a6b-85f0-f8a78d823588', tracking id '43fc5463-795c-47c1-9ff3-560e717832cb', request correlation id '53a07538-42ef-7114-a804-1b3f9e20ef5a'.\"}}",
        "responseBody": "{\"error\":{\"code\":\"InternalServerError\",\"message\":\"Encountered internal server error. Diagnostic information: timestamp '20210602T072802Z', subscription id '53621724-10de-4a6b-85f0-f8a78d823588', tracking id '43fc5463-795c-47c1-9ff3-560e717832cb', request correlation id '53a07538-42ef-7114-a804-1b3f9e20ef5a'.\"}}",
        "eventCategory": "Administrative",
        "entity": "/subscriptions/53621724-10de-4a6b-85f0-f8a78d823588/resourceGroups/stagingfw02-RG/providers/Microsoft.Compute/virtualMachines/stagingfw02-B-VM-FGT",
        "message": "Microsoft.Compute/virtualMachines/write",
        "hierarchy": "b388b808-0ec9-4a09-a414-a7cbbd8b7e9b/PODNET/53621724-10de-4a6b-85f0-f8a78d823588"
    },
    "relatedEvents": []

**Comment by oappiah** [comment]
Hi ,
I managed to run both Active-Passive-ELB-ILB and VNET-Peering without an issue.

Cloned this repo , ran the deploy.sh in the folder. 
When prompted: 
I picked a new RG , used northeurope as region, default user,  picked a password that meets the password complexity .

@HeShaobo1 did you change the script or any tf files? Tried another region?

**Comment by HeShaobo1** [comment]
HI Oappiah,
first of all, i faced another issue with availability, failed to pass terraform plan with an error told me the fault 1-2 is acceptable, so I add the platform_fault_domain_count  as the document suggested.https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/availability_set

resource "azurerm_availability_set" "fgtavset" {
  name                = "${var.PREFIX}-FGT-AVSET"
  location            = var.LOCATION
  managed             = true
  **platform_fault_domain_count = 2**
  resource_group_name = azurerm_resource_group.resourcegroup.name
}

All i changed in  the terraform in 02-fortigate.tf, line 12.

I can only deployment in China East, but sorry it failed two.

**Comment by HeShaobo1** [comment]
HI Oappiah,
First of all, yes, I changed tf file named 02-fortigate.tf . Due to i faced another issue with availability, failed to pass terraform plan with an error told me the fault 1-2 is acceptable, so I add the platform_fault_domain_count as the document suggested.https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/availability_set
the error:
Error: compute.AvailabilitySetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The specified fault domain count 3 must fall in the range 1 to 2." Target="platformFaultDomainCount"

  on 02-fortigate.tf line 8, in resource "azurerm_availability_set" "fgtavset":
   8: resource "azurerm_availability_set" "fgtavset" {


The solution tf I changed:
Add the  into \fortinet-azure-solutions-main\fortinet-azure-solutions-main\FortiGate\Terraform\Active-Passive-ELB-ILB\terraform\02-fortigate.tf , in line 12
resource "azurerm_availability_set" "fgtavset" {
name = "${var.PREFIX}-FGT-AVSET"
location = var.LOCATION
managed = true
platform_fault_domain_count = 2
resource_group_name = azurerm_resource_group.resourcegroup.name
}


Then, all goes well with terraform init, plan, but error when applying with the following error  after 7m30s time out:

azurerm_virtual_machine.fgtbvm: Still creating... [7m30s elapsed]
Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20210603T054518Z', subscription id '53621724-10de-4a6b-85f0-f8a78d823588', tracking id '29b96557-11c6-4fdd-a28b-61db3248ae33', request correlation id '114d7aca-e2c5-9481-4ebd-e4beb4a45f35'."

  on 02-fortigate.tf line 245, in resource "azurerm_virtual_machine" "fgtavm":
 245: resource "azurerm_virtual_machine" "fgtavm" {



Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError" Message="Encountered internal server error. Diagnostic information: timestamp '20210603T054518Z', subscription id '53621724-10de-4a6b-85f0-f8a78d823588', tracking id '3d61f743-090c-4104-88e7-164644bb0981', request correlation id '114d7aca-e2c5-9481-4ebd-e4beb4a45f35'."

  on 02-fortigate.tf line 432, in resource "azurerm_virtual_machine" "fgtbvm":
 432: resource "azurerm_virtual_machine" "fgtbvm" {



So in my personal perspective, i think the OS Publisher is not existed in China Region. because China only has fortinet-cn.

PS C:\Users\usertest> Get-AzVMImagePublisher -Location 'China East 2' | findstr fortinet
fortinet-cn                                     ChinaEast2 /Subscriptions/53621724-10de-4a6b-85f0-f8a78d823588/Providers/Microsoft.Com...

PS C:\Users\usertest> 
PS C:\Users\usertest> 
PS C:\Users\usertest> Get-AzVMImagePublisher -Location 'China East' | findstr fortinet
fortinet-cn                                               chinaeast /Subscriptions/53621724-10de-4a6b-85f0-f8a78d823588/Providers/Micr...

PS C:\Users\usertest> 
PS C:\Users\usertest> 
PS C:\Users\usertest> Get-AzVMImagePublisher -Location 'China North' | findstr fortinet
fortinet-cn                 

Can you help me to adjust the tf with the formal China FortiGate VM OS? hope the following commands results will be helpful.

PS C:\Users\usertest> Get-AzVMImage -Location 'China North 2' -PublisherName fortinet-cn -Offer "fortinet_fortigate-vm_v6_0" -Skus "fortinet_fg-vm_6_0"

Version FilterExpression Skus               Offer                      PublisherName Location    Id            
------- ---------------- ----               -----                      ------------- --------    --            
1.0.1                    fortinet_fg-vm_6_0 fortinet_fortigate-vm_v6_0 fortinet-cn   ChinaNorth2 /Subscripti...
6.2.3                    fortinet_fg-vm_6_0 fortinet_fortigate-vm_v6_0 fortinet-cn   ChinaNorth2 /Subscripti...

Thanks in advance.

**Comment by HeShaobo1** [comment]
And in addition, all I tried in 4 Azure China Region failed with this solution, facing same error when creating fortinet vm.

Thanks.

**Comment by oappiah** [comment]
I don't have any subscription that can deploy in Azure China also I can't find these offers you listed ( they seem older) in my available regions , so I can't test myself.

You can _try_ modifying these but I dobut these templates were tested for those.

https://github.com/40net-cloud/fortinet-azure-solutions/blob/d553abe0c120ba0016a6ed9d1b295fb493252ced/FortiGate/Terraform/VNET-Peering/terraform/03-fortigate.tf#L292-L296
https://github.com/40net-cloud/fortinet-azure-solutions/blob/d553abe0c120ba0016a6ed9d1b295fb493252ced/FortiGate/Terraform/VNET-Peering/terraform/00-general.tf#L32-L35

But that's probably the issue , I would expect a better error from Azure then a Error 500!

**Comment by HeShaobo1** [comment]
Dear Oappiah,

Thanks for your feedback, I will try and modify as you suggested for Azure China OS， will keep you updated.

Thanks again.

**Comment by HeShaobo1** [comment]
Dear Oappiah,

Goodday, thanks for your great help, the issue was solved by changing the OS publisher. 


   storage_image_reference  {
    publisher = "fortinet-cn"
    offer     = "fortinet_fortigate-vm_v6_0"
    sku       = "fortinet_fg-vm_6_0"
    version   = "6.2.3"
  }


  storage_os_disk {
    name              = "${var.PREFIX}-A-VM-FGT-OSDISK"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

The issue can be closed now, thanks again.
