### ISSUE TITLE
How to add Vnet to Vnet Peering in this design?

### ISSUE THREAD

**Issue by gpp-infrastructure** [40net-cloud/fortinet-azure-solutions#93]
Love what you have done with these templates, so easy to deploy and with different scenarios.  We want to use [AvailabilityZones/Active-Active-ELB-ILB-AZ](https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/AvailabilityZones) and it works well, but now we also want to do Vnet peering, and its a bit confusing to select the [FortiGate/VNET-Peering/](https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/VNET-Peering) as that is only Active-Passive?

Any guidance would be appreciated.

**Comment by jvhoof** [comment]
Hi,

The VNET peering is a demo of the Cloud Security Services Hub. You can build it on your own as well using any of the building blocks (single, A/P, A/A). 

The A/P method resembles mostly what most customers have on-premise and removes the requirement for SNAT or FGSP. Just deploy the A/A setup and you can peer any existing VNET as a spoke to this HUB. Configure the UDR routing correctly and you are up and running. 

Hope this will work for you. If you have any additional questions let us know.

Joeri

**Comment by gpp-infrastructure** [comment]
Hi Joeri.

Thanks for the quick response. We have tried the peering with UDR to the internal lb, and it didn't work. After quite a bit of back and forth, we added a static route on the Fortigate to the peered vnet with the internal nic(port2) as the gateway. Working perfectly now.

thanks again for these templates :)

**Comment by jvhoof** [comment]
Good to hear!

Keep the questions and comments coming to make these templates better.

Joeri
